### ISSUE TITLE
Weird Darkness Glitch

### ISSUE THREAD

**Issue by istupidgirl** [HowardZHY/Phosphor-Legacy-Forge#1]
This happens after creating, then leaving & rejoining a single player world multiple times. I only have this mod installed.

![2024-03-04_19 57 16](https://github.com/HowardZHY/Phosphor-Legacy-Forge/assets/88780152/78d11f7e-46df-4773-83ab-f2bef8e0ce2c)
![2024-03-04_20 01 49](https://github.com/HowardZHY/Phosphor-Legacy-Forge/assets/88780152/2a896a86-2944-4cfa-87c1-06f3ea4c3306)

**Comment by HowardZHY** [comment]
I'm trying to figure this since last week, I'll make a notice atm

**Comment by HowardZHY** [comment]
I've compared codes with Hesperus, Phosphor Legacy and ArchaicFix but still no luck after changed many things, it's weird that serverside skylight is 0 and sometimes blocklight to be 15 when re loading the chunks like re entering the world at night

**Comment by HowardZHY** [comment]
More info: this also happens at the world border when changing View Distance multiple times, and seems only happens in the Overworld
If you create a singleplayer superflat world you'll se how broken it is...
In The Nether, there are black chunk boundary on the lava sea

**Comment by HowardZHY** [comment]
https://github.com/RelativityMC/C2ME-fabric/issues/7 
This looks similar

**Comment by HowardZHY** [comment]
Grayray thought this is 98% Forge breaking stuffs

**Comment by HowardZHY** [comment]
@kianfakheriaghdam https://github.com/HowardZHY/Phosphor-Legacy-Forge/releases/tag/5 should fix it

**Comment by HowardZHY** [comment]
https://github.com/HowardZHY/Phosphor-Legacy-Forge/commit/2552c793597d090712a3d1a969a66b8a7e97c077

**Comment by istupidgirl** [comment]
> [2552c79](https://github.com/HowardZHY/Phosphor-Legacy-Forge/commit/2552c793597d090712a3d1a969a66b8a7e97c077)

great work. dont forget to update on modrinth
